### ISSUE TITLE
Add main menu as first scene

### ISSUE THREAD

**Issue by PhoenixFlame101** [PhoenixFlame101/pong-with-godot#2]
## The Problem

Right now the game starts immediately on launch, which is obviously not ideal. To solve this issue, a main menu has to be made.

## Possible Solutions

The main menu should be on a different scene and should start the game on pressing a UI button or a key/mouse button while the window is in focus. It should also show 'Pong with Godot' as the title (obviously).

---
 - Block time: 30 mins (You need to give updates every 30 mins if you have been assigned)
 - Bounty points: 80

**Comment by architanand95** [comment]
could you assign this to me

**Comment by PhoenixFlame101** [comment]
Sure, go ahead!

**Comment by PhoenixFlame101** [comment]
Hey @architanand95 what's the progress on the issue?

**Comment by architanand95** [comment]
sorry bro its u can pass it to someone else

**Comment by PhoenixFlame101** [comment]
Sure np

**Comment by Vaarun-C** [comment]
Hey can I be assigned to this :)

**Comment by Harshit-crypto** [comment]
hi can i work on this? @PhoenixFlame101

**Comment by PhoenixFlame101** [comment]
@Vaarun-Kamath do you want to abandon your PR? You have not requested to be assigned.
