### ISSUE TITLE
Add game over screen when the ball goes out of bounds

### ISSUE THREAD

**Issue by PhoenixFlame101** [PhoenixFlame101/pong-with-godot#3]
## The Problem

Currently the game just restarts automatically if the ball goes out of bounds. The task is to create a game over screen when this happens.

## Possible Solutions

Create a game over screen with two buttons: A restart button to start the game again, and another to exit to main menu. (If the main menu has not be merged to the master branch, you can make this a dummy button that doesn't do anything).

---
 - Block time: 30 mins (You need to give updates every 30 mins if you have been assigned)
 - Bounty points: 80

**Comment by Vaarun-Kamath** [comment]
hey can i work on this pls :)

**Comment by snaupdog** [comment]
Can you assign this to me pls
PES2202200828
Nihal satish

**Comment by PhoenixFlame101** [comment]
@snaupdog This issue has almost been fixed, and will be closed soon

**Comment by Vaarun-Kamath** [comment]
is it fine?
