### ISSUE TITLE
Make the game more high octance

### ISSUE THREAD

**Issue by PhoenixFlame101** [PhoenixFlame101/pong-with-godot#4]
## The Problem

The game is really slow and boring right now, make it a bit faster.

## Possible Solutions

Change the speeds of the paddle and ball to be a bit faster than they already are. Make sure the game is still playable.

---
 - Block time: 10 mins (You need to give updates every 10 mins if you have been assigned)
 - Bounty points: 20

**Comment by tnayagarwal** [comment]
can i get this @PhoenixFlame101

**Comment by PhoenixFlame101** [comment]
Sure, done.

**Comment by mokshablr** [comment]
can i get this assigned? @PhoenixFlame101

**Comment by PhoenixFlame101** [comment]
If @tnayagarwal has abandoned the PR they made then I'll assign

For now the issue is taken

**Comment by PhoenixFlame101** [comment]
@tnayagarwal please comment now if you still want to work on this or else I'll unassign you

**Comment by tnayagarwal** [comment]
@PhoenixFlame101 submitting in a min sorry got confused
